version: '3'
services:
  imgproxy:
    build:
      context: ./imgproxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"

  redis:
    image: "redis:6-alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"

  qdrant:
    image: "qdrant/qdrant"
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - /app/data/qdrant:/qdrant/storage


