version: '3'
services:
  vector:
    # image: "timberio/vector:latest-debian"
    build:
      context: ./vector

    networks:
      - my-custom-network
    # restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./vector/vector.yaml:/etc/vector/vector.yaml"
      - "/var/log/nginx:/var/log/nginx"


networks:
  my-custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
        - subnet: "2001:db8::/64"
          gateway: "2001:db8::1"



    
    # enable_ipv6: true



  # imgproxy:
  #   build:
  #     context: ./imgproxy
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"

  # redis:
  #   image: "redis:6-alpine"
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"

  # qdrant:
  #   image: "qdrant/qdrant"
  #   restart: unless-stopped
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - /app/data/qdrant:/qdrant/storage


