type: "http"
method: "post"
uri: "https://in.logs.betterstack.com/"
encoding:
  codec: "json"
auth:
  strategy: "bearer"
  token: "${VECTOR_MISC_LOGS_BEARER_TOKEN}"
inputs: 
  - transform_docker_router._unmatched
