type: "http"
method: "post"
uri: "https://in.logs.betterstack.com/"
encoding:
  codec: "json"
auth:
  strategy: "bearer"
  token: "${VECTOR_GO_CRON_LOGS_BEARER_TOKEN}"
inputs:
  - transform_go_cron_logs